### ISSUE TITLE
Fraudulent DESCRIPTION file

### ISSUE THREAD

**Issue by Ironholds** [RBigData/pbdML#1]
According to the GitHub statistics only 5.6% of the package is written in C. Accordingly there's no way in hell Drew wrote it ;p.

**Comment by wrathematics** [comment]
Hah, well it's supposed to be a demonstration of pbdDMAT, which is like the matrix package for distributed matrices.  Really it shouldn't have any C code in it :[

**Comment by Ironholds** [comment]
So I should open issue number 2, "has too MUCH C in it"? ;)

**Comment by wrathematics** [comment]
> "has too MUCH C in it"

WONTFIX

**Comment by Ironholds** [comment]
:D
